# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculator2.proto\x12\ncalculator\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x02\"\'\n\x0fSubtractRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\"\n\x10SubtractResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\"\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\"%\n\rDivideRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\" \n\x0e\x44ivideResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\x9b\x02\n\nCalculator\x12\x38\n\x03\x41\x64\x64\x12\x16.calculator.AddRequest\x1a\x17.calculator.AddResponse\"\x00\x12G\n\x08Subtract\x12\x1b.calculator.SubtractRequest\x1a\x1c.calculator.SubtractResponse\"\x00\x12G\n\x08Multiply\x12\x1b.calculator.MultiplyRequest\x1a\x1c.calculator.MultiplyResponse\"\x00\x12\x41\n\x06\x44ivide\x12\x19.calculator.DivideRequest\x1a\x1a.calculator.DivideResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDREQUEST._serialized_start=33
  _ADDREQUEST._serialized_end=67
  _ADDRESPONSE._serialized_start=69
  _ADDRESPONSE._serialized_end=98
  _SUBTRACTREQUEST._serialized_start=100
  _SUBTRACTREQUEST._serialized_end=139
  _SUBTRACTRESPONSE._serialized_start=141
  _SUBTRACTRESPONSE._serialized_end=175
  _MULTIPLYREQUEST._serialized_start=177
  _MULTIPLYREQUEST._serialized_end=216
  _MULTIPLYRESPONSE._serialized_start=218
  _MULTIPLYRESPONSE._serialized_end=252
  _DIVIDEREQUEST._serialized_start=254
  _DIVIDEREQUEST._serialized_end=291
  _DIVIDERESPONSE._serialized_start=293
  _DIVIDERESPONSE._serialized_end=325
  _CALCULATOR._serialized_start=328
  _CALCULATOR._serialized_end=611
# @@protoc_insertion_point(module_scope)
