spec:
   template:
      metadata:
         labels:
            app.kubernetes.io/instance: app-python
            app.kubernetes.io/name: app-python
         annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'internal-app'
            vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config'

