#!/bin/python
import time
print("Для начала, четко и ясно напиши, зачем тебе нужно сейчас открыть телеграм")
time.sleep(1)
print("Опиши коротко, какое конкретное действие ты хочешь сделать, и сколько времени оно у тебя займет")
print("Что ты сделаешь, когда его выполнишь, и тд")
time.sleep(5)
print("И помни - никаких левых прокрастинаций и подобного.")
print("Нет времени на детские штучки, тебе еще столько всего надо сделать, ты же ведь не хочешь просрать свою жизнь впустую?!")
s = input()

MIN_CHARS = 50
MIN_UNIQ_CHARS = 13

while len(s) < MIN_CHARS or len(set(s)) < MIN_UNIQ_CHARS:
    print(f"Недостаточно убедительно! ({len(s)}<{MIN_CHARS} {len(set(s))}<{MIN_UNIQ_CHARS})")
    s = input()

# print(s)

import subprocess
subprocess.call('sudo ./.Telegram'.split())
